const trips = [
  {
    destinationName: "París, Francia",
    description:
      "La ciudad del amor, famosa por su arte, gastronomía y monumentos.",
    dates: "10/03/2026 - 17/03/2026",
    price: 1200,
    reviews: 324,
    rating: 4.8,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Roma, Italia",
    description: "Historia viva con ruinas antiguas y una cocina incomparable.",
    dates: "05/04/2026 - 12/04/2026",
    price: 1100,
    reviews: 289,
    rating: 4.7,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Tokio, Japón",
    description: "Tecnología, tradición y cultura en perfecta armonía.",
    dates: "20/05/2026 - 30/05/2026",
    price: 2100,
    reviews: 412,
    rating: 4.9,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Nueva York, Estados Unidos",
    description: "La ciudad que nunca duerme, llena de energía y diversidad.",
    dates: "01/06/2026 - 08/06/2026",
    price: 1500,
    reviews: 530,
    rating: 4.6,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Cancún, México",
    description: "Playas paradisíacas y resorts todo incluido.",
    dates: "15/07/2026 - 22/07/2026",
    price: 1300,
    reviews: 610,
    rating: 4.5,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Barcelona, España",
    description: "Arte, playa y arquitectura modernista.",
    dates: "10/09/2026 - 17/09/2026",
    price: 1000,
    reviews: 275,
    rating: 4.7,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Londres, Inglaterra",
    description: "Historia, cultura y modernidad en una sola ciudad.",
    dates: "02/10/2026 - 09/10/2026",
    price: 1400,
    reviews: 390,
    rating: 4.6,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Bali, Indonesia",
    description: "Naturaleza, playas y espiritualidad.",
    dates: "05/11/2026 - 15/11/2026",
    price: 1800,
    reviews: 458,
    rating: 4.9,
    image: "/assets/unnamed.jpg",
  },
  {
    destinationName: "Dubái, Emiratos Árabes Unidos",
    description: "Lujo, modernidad y desierto.",
    dates: "01/12/2026 - 08/12/2026",
    price: 2000,
    reviews: 340,
    rating: 4.8,
    image: "/assets/unnamed.jpg",
  },
];

export default trips;
