spring.application.name=tfg

server.port=8080

#conection to mysql
spring.datasource.url=${DATASOURCE_URL:jdbc:mysql://localhost:3306/tfg}
spring.datasource.username=${DATASOURCE_USERNAME:root}
spring.datasource.password=${DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

#Data for JWT
jwt.secret=${JWT_SECRET:TheBestDuoForeverJanireAndMateoRealGForLifeMyBabyAhoraYaNoSeNiQuePonerParaQueEstaClaveEncripteASuMismisimaPTM}
jwt.expiration=${JWT_EXPIRATION:120}
jwt.refresh-threshold=${JWT_REFRESH_THRESHOLD:15}

#credentials for cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:matthew1010100}
cloudinary.api_key=${CLOUDINARY_API_KEY:769712583249861}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:cui0TQTW1LLh4Q6R6YL6RXeV9DM}

#config to allow uploading file-size until 8MB
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

#Resend
resend.api_key=${RESEND_API_KEY:re_fMukRudy_FxXV7zexPYmeAxhpX28PYrau}
resend.domain=${RESEND_DOMAIN:noreply@api-project-jani-and-mat.com}

#OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#Contact
contact.email=${CONTACT_EMAIL:aventuratrips2026@gmail.com}

#Profile picture default URL
profile.picture.default=https://res.cloudinary.com/matthew1010100/image/upload/v1771056021/profile_xbqujh.webp
